import { z } from 'zod'

export const cabinetSchema = z.object({
  id: z.string().describe('ID кабинета').nullable(),
  userId: z.string().describe('ID пользователя').nullable(),
  type: z.enum(['wildberries', 'fulfillment']).describe('Тип организации').nullable(),
  inn: z.string().describe('ИНН').nullable(),
  legalCompanyName: z.string().describe('Юридическое название организации').nullable(),
  companyName: z.string().describe('Название компании (для отображения)').nullable().nullish(),
  number1: z.string().describe('Номер первого уровня').nullable(),
  number2: z.string().describe('Номер второго уровня').nullable(),
  createdAt: z.date().describe('Дата создания').nullable(),
  updatedAt: z.date().describe('Дата обновления').nullable(),
  verifiedAt: z.date().describe('Дата верификации').nullable(),
  avatarUrl: z.string().describe('URL аватарки кабинета').nullable(),
  apiKey: z.string().describe('API ключ Wildberries').nullable().nullish(),
  isVerified: z.boolean().describe('Статус верификации кабинета').nullable(),
  isActive: z.boolean().describe('Статус активности кабинета').nullable(),
  ogrn: z.string().describe('ОГРН организации').nullable(),
  managerFullName: z.string().describe('ФИО управляющего').nullable(),
  legalAddress: z.string().describe('Юридический адрес').nullable(),
  actualAddress: z.string().describe('Фактический адрес').nullable(),
  companyPhone: z.string().describe('Телефон организации').nullable(),
  companyEmail: z.string().describe('Email организации').nullable(),
  telegramUrl: z.string().describe('Ссылка на Telegram').nullable(),
  whatsappUrl: z.string().describe('Ссылка на WhatsApp').nullable(),
  bankName: z.string().describe('Название банка').nullable(),
  bik: z.string().describe('БИК банка').nullable(),
  checkingAccount: z.string().describe('Расчетный счет').nullable(),
  correspondentAccount: z.string().describe('Корреспондентский счет').nullable(),
  registrationUrl: z.string().describe('Ссылка для регистрации партнеров').nullable(),
  partners: z.array(z.lazy(() => cabinetSchema)).describe('Связанные кабинеты (где этот кабинет является партнером)'),
  verificationComment: z.string().describe('Комментарий администратора при верификации').nullable().nullish(),
  blockedAt: z.date().describe('Дата блокировки').nullable(),
})