services:
  sphere-frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: sphere-frontend:${TAG:-latest}
    container_name: sphere-frontend
    restart: unless-stopped
    ports:
      - "3014:3000"
    environment:
      # Next.js конфигурация
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      
      # API конфигурация
      - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      
      # NextAuth конфигурация
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      
      # Дополнительные переменные
      - FRONTEND_URL=${FRONTEND_URL}
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - sphere-frontend-network
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sphere-frontend-network:
    driver: bridge 