services:
  sphere-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - NEXT_PUBLIC_API=https://api.sferav.ru
        - NEXT_PUBLIC_API_URL=https://api.sferav.ru
        - NEXT_PUBLIC_API_KEY=8fda9283-6ed8-45fa-a9e6-75d84a7b90f1
        - NEXTAUTH_URL=https://sferav.ru
        - NEXTAUTH_SECRET=secret
    container_name: sphere-frontend
    restart: unless-stopped
    ports:
      - "3014:3000"
    environment:
      # Next.js конфигурация
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
      
      # API конфигурация (жестко заданные значения)
      - NEXT_PUBLIC_API=https://api.sferav.ru
      - NEXT_PUBLIC_API_URL=https://api.sferav.ru
      - NEXT_PUBLIC_API_KEY=8fda9283-6ed8-45fa-a9e6-75d84a7b90f1
      
      # NextAuth конфигурация
      - NEXTAUTH_URL=https://sferav.ru
      - NEXTAUTH_SECRET=secret
      
      # Дополнительные переменные
      - FRONTEND_URL=https://sferav.ru
      - KUBB_API_URL=https://api.sferav.ru/api-json
    
    networks:
      - sphere-frontend-network
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sphere-frontend-network:
    driver: bridge 